// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel KernelHashDeepShadowMap

#include "../Include/DeepShadowMap.cginc"
RWStructuredBuffer<HeaderNode> HeaderList;
RWStructuredBuffer<LinkedNode> LinkedList;

[numthreads(1,1,1)]
void KernelHashDeepShadowMap (uint3 id : SV_DispatchThreadID)
{
    int originalVal;
    uint idx = LinkedList[id.x].index;
    InterlockedExchange(HeaderList[idx].start, id.x, originalVal);
    LinkedList[id.x].next = originalVal;
}
